baseurl = "http://blog.drj.tools/"
languageCode = "en-us"
title = "notes"
theme = "nofancy"
copyright = "Copyright (c) 2016 David R. Jenni. All rights reserved."

[author]
	name = "David R. Jenni"
	github = "davidrjenni"
	twitter = "davidrjenni"
	gaID = "UA-73273600-1"
