baseurl = "http://blog.drj.tools/"
languageCode = "en-us"
title = "notes"
theme = "nofancy"
copyright = "Copyright © 2016–2017 David R. Jenni. All rights reserved."

[author]
	name = "David R. Jenni"
	github = "davidrjenni"
	twitter = "davidrjenni"
	linkedin = "davidrjenni"
	keybase = "davidrjenni"
	googleplus = "+DavidRJenni"
